# Generated by Django 5.2.1 on 2025-05-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_project_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='No description provided', max_length=1000),
        ),
    ]
