# Generated by Django 5.2.1 on 2025-05-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField()),
                ('role', models.CharField()),
                ('domin', models.CharField()),
                ('github', models.URLField(default='')),
                ('linkden', models.URLField(default='')),
                ('facebook', models.URLField(default='')),
                ('portfolio', models.URLField(default='')),
            ],
        ),
    ]
