# Generated by Django 5.2.1 on 2025-05-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='description',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='personal',
            name='location',
            field=models.CharField(default=''),
        ),
    ]
